linters:
  enable:
    - govet
    - gosec
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - structcheck
    - varcheck
    - ineffassign
    - deadcode
    - typecheck
  disable-all: false
