name: CI Workflow
on:
  pull_request:
    branches:
    - main

jobs:

  lint:
    name: Linter Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          # Required: the version of golangci-lint is required and must be specified without patch version: we always use the latest patch version.
          version: v1.30

  test:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.15
    - name: Checkout
      uses: actions/checkout@v1
    - name: Run unit tests
      run: make test
